const products = {
  spot:{label:'Spot trading',short:'Spot',color:'#EB4646',default:20,desc:'Buy or sell the underlying asset without borrowing.'},
  futures:{label:'Futures collateral',short:'Futures',color:'#C96A6A',default:15,desc:'Margin reserved for perpetual positions; losses can reduce equity.'},
  stocks:{label:'Stocks / TradFi',short:'Stocks',color:'#A94B4B',default:10,desc:'Exposure to supported equity and traditional markets where available.'},
  lending:{label:'Lending',short:'Lending',color:'#F4F4F6',default:25,desc:'Supply assets to a lending pool; the rate can move over time.'},
  borrow:{label:'Borrowing (debt)',short:'Borrow',color:'#777C8A',default:0,desc:'Modeled debt backed by collateral; interest and liquidation risk apply.'},
  reserve:{label:'Safety reserve',short:'Reserve',color:'#4D515D',default:30,desc:'Capital kept unallocated so the plan has room to breathe.'}
};
const presets = {
  preserve:{spot:10,futures:0,stocks:5,lending:35,borrow:0,reserve:50},
  balanced:{spot:20,futures:15,stocks:10,lending:25,borrow:0,reserve:30},
  explore:{spot:25,futures:25,stocks:15,lending:20,borrow:5,reserve:10}
};
const faq = [
  ['Spot trading','Spot is the straightforward version of trading: you exchange one asset for another and own the asset you bought. There is no leverage in this bucket.'],
  ['Futures collateral','A futures position uses collateral to support a long or short contract. The position can be larger than the collateral, so the stress test treats this bucket as the highest-risk allocation.'],
  ['Lending','Lending means supplying assets to Backpack’s lending market so other participants can borrow them. You receive a variable rate; the calculator never treats it as guaranteed income.'],
  ['Borrowing','Borrowing means taking a loan against eligible collateral. The borrowed amount is debt—not extra free profit—and interest plus market moves can increase risk.'],
  ['Safety reserve','A reserve is money you intentionally leave out of active strategies. It can help absorb volatility, fees, or a margin top-up without forcing a rushed decision.'],
  ['Cross-margin & one balance','Backpack is designed around one balance across supported products. In this planner, that is represented as a composition—not a promise that every asset or market has identical collateral treatment.'],
  ['Variable income','The income range is an illustrative monthly estimate based on a conservative placeholder lending rate and modeled borrowing cost. Connect live Backpack rates before using it for a real decision.']
];
let state = {capital:1000,horizon:1,risk:'balanced',goal:'steady',lendingRate:6,borrowRate:10,allocations:{...presets.balanced},mode:'simple',radarData:null};
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const money = n => '$' + Math.round(Math.max(0,n)).toLocaleString('en-US');
const pct = n => `${Math.round(n)}%`;
function renderAllocations(){
  $('#allocations').innerHTML = Object.entries(products).map(([key,p])=>`<div class="allocation-row" data-key="${key}"><div class="allocation-meta"><div class="allocation-label"><i class="swatch" style="background:${p.color}"></i>${p.label}</div><div class="allocation-values"><strong id="amount-${key}">${money(state.capital*state.allocations[key]/100)}</strong><span id="pct-${key}">${pct(state.allocations[key])}</span></div></div><div class="allocation-desc">${p.desc}</div><input class="range" data-key="${key}" type="range" min="0" max="100" step="1" value="${state.allocations[key]}" style="--fill:${state.allocations[key]}%" aria-label="${p.label} allocation" /></div>`).join('');
  $$('.range').forEach(el=>el.addEventListener('input',()=>adjustAllocation(el.dataset.key,Number(el.value))));
}
function adjustAllocation(key,value){
  const previous = state.allocations[key]; let delta = value-previous; state.allocations[key]=value;
  const order = ['reserve','lending','spot','stocks','futures','borrow'].filter(k=>k!==key);
  for(const other of order){ if(!delta) break; const available = delta>0 ? state.allocations[other] : 100-state.allocations[other]; const shift = Math.min(Math.abs(delta),available)*(delta>0?-1:1); state.allocations[other]+=shift; delta += shift; }
  state.allocations[key] -= delta;
  Object.keys(products).forEach(k=>state.allocations[k]=Math.max(0,Math.min(100,state.allocations[k])));
  renderAllocations(); recalculate();
}
function setPreset(name){state.allocations={...presets[name]}; $$('.preset').forEach(b=>b.classList.toggle('current',b.dataset.preset===name)); renderAllocations(); recalculate();}
function conicGradient(){let start=0; const chunks=[]; for(const [key,p] of Object.entries(products)){const end=start+state.allocations[key]; chunks.push(`${p.color} ${start}% ${end}%`); start=end;} return `conic-gradient(${chunks.join(',')})`;}
function recalculate(){
  const a=state.allocations,c=state.capital; const reserve=c*a.reserve/100; const lending=c*a.lending/100; const borrow=c*a.borrow/100; const active=c*(a.spot+a.futures+a.stocks)/100;
  const leverage=state.risk==='low'?1.5:state.risk==='high'?5:3; const stress=active*0.1+(c*a.futures/100)*(leverage-1)*0.1; const annualRate=Math.max(0,Number(state.lendingRate)||0)/100; const gross=lending*annualRate*(state.horizon/12); const borrowCost=borrow*(Math.max(0,Number(state.borrowRate)||0)/100)*(state.horizon/12); const upper=Math.max(0,gross-borrowCost);
  $('#donut').style.background=conicGradient(); $('#mapCapital').textContent=money(c); $('#productive').textContent=money(c-reserve); $('#reserve').textContent=money(reserve); $('#income').textContent=`${money(0)}–${money(upper)}`; $('#incomeSub').textContent=`variable carry over ${state.horizon} ${state.horizon===1?'month':'months'}`; $('#stress').textContent=`-${money(stress)} impact`;
  const riskName=state.risk[0].toUpperCase()+state.risk.slice(1); $('#riskLabel').textContent=riskName; $('#riskSub').textContent=state.risk==='low'?'larger buffer · lower exposure':state.risk==='high'?'thin buffer · amplified moves':'moderate exposure · balanced buffer'; $('#totalPct').textContent=pct(Object.values(a).reduce((x,y)=>x+y,0));
  $('#legend').innerHTML=Object.entries(products).map(([key,p])=>`<div class="legend-item"><span><i class="swatch" style="background:${p.color}"></i>${p.short}</span><strong>${pct(a[key])}</strong></div>`).join('');
  const total=Object.values(a).reduce((x,y)=>x+y,0); $('#allocationWarning').classList.toggle('hidden',Math.round(total)===100);
  let message = a.reserve<15 ? 'Your reserve is thin. A smaller active allocation can reduce the chance of a forced decision during a sharp move.' : a.lending>35 ? 'This plan leans on lending. Rates move, so treat the income range as variable and keep a reserve visible.' : a.futures>25 ? 'Futures are doing most of the heavy lifting here. Lower leverage and a wider reserve can make the plan more resilient.' : a.borrow>0 ? 'Borrowing can make capital more flexible, but debt and interest remain even when markets move against you.' : 'A visible reserve gives this composition room to breathe while you explore Backpack’s connected products.'; $('#insight p').textContent=message;
  const suggestions={steady:['Income-first starting point','Keep 40–60% in reserve, lend only the portion you can leave untouched, and keep futures small.'],growth:['Diversified growth starting point','Use a measured split across spot, stocks and lending; treat futures as a capped learning allocation, not a target return.'],learn:['Learning-first starting point','Use small spot and futures amounts, keep most capital in reserve or lending, and review the stress test before increasing exposure.']}; $('#recommendation strong').textContent=suggestions[state.goal][0]; $('#recommendation p').textContent=suggestions[state.goal][1];
  Object.entries(products).forEach(([key,p])=>{const amt=$(`#amount-${key}`), pp=$(`#pct-${key}`); if(amt)amt.textContent=money(c*a[key]/100); if(pp)pp.textContent=pct(a[key]);});
  const title=`${money(c)} · ${riskName}`; $('#cardTitle').textContent=title; $('#cardSubtitle').textContent=`${pct(a.reserve)} reserve · ${pct(a.lending)} lending · ${pct(a.spot+a.futures+a.stocks)} active`; $('#miniBars').innerHTML=Object.entries(products).map(([key,p])=>`<i class="mini-bar" title="${p.label}: ${pct(a[key])}" style="height:${Math.max(8,a[key]*.8)}px;background:${p.color}"></i>`).join(''); $('#shareId').textContent=`PLAN / ${hashCode(JSON.stringify({c,state}))}`;
}
function hashCode(str){let h=0; for(let i=0;i<str.length;i++)h=((h<<5)-h)+str.charCodeAt(i)|0; return Math.abs(h).toString(16).toUpperCase().padStart(6,'0').slice(-6);}
function encodePlan(){const payload=btoa(JSON.stringify(state)); return `${location.origin}${location.pathname}#plan=${payload}`;}
function loadPlan(){const raw=location.hash.startsWith('#plan=')?location.hash.slice(6):''; if(!raw)return; try{const parsed=JSON.parse(atob(raw)); if(parsed&&parsed.allocations){state={...state,...parsed,allocations:{...state.allocations,...parsed.allocations}}; $('#capital').value=state.capital; $('#horizon').value=state.horizon; $('#risk').value=state.risk; $('#goal').value=state.goal||'steady'; $('#lendingRate').value=state.lendingRate??6; $('#borrowRate').value=state.borrowRate??10; renderAllocations(); recalculate();}}catch(e){console.warn('Could not load plan',e)}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
async function copyPlan(){try{await navigator.clipboard.writeText(encodePlan());toast('Share link copied')}catch(e){toast('Copy failed — use your browser address bar')}}
function initFaq(){$('#faqList').innerHTML=faq.map((item,i)=>`<div class="faq ${i===0?'open':''}"><button aria-expanded="${i===0}"><span>${item[0]}</span><span>${i===0?'−':'+'}</span></button><div class="faq-answer">${item[1]}</div></div>`).join(''); $$('.faq button').forEach(btn=>btn.addEventListener('click',()=>{const parent=btn.parentElement;parent.classList.toggle('open');btn.setAttribute('aria-expanded',parent.classList.contains('open'));btn.lastElementChild.textContent=parent.classList.contains('open')?'−':'+';}))}
function reset(){state={capital:1000,horizon:1,risk:'balanced',goal:'steady',lendingRate:6,borrowRate:10,allocations:{...presets.balanced},mode:'simple'};$('#capital').value=1000;$('#horizon').value=1;$('#risk').value='balanced';$('#goal').value='steady';$('#lendingRate').value=6;$('#borrowRate').value=10;$$('.preset').forEach(b=>b.classList.toggle('current',b.dataset.preset==='balanced'));renderAllocations();recalculate();history.replaceState(null,'',location.pathname);toast('Plan reset')}
function renderModal(){const source=$('.share-preview');$('#modalCard').innerHTML=source.innerHTML;$('#xShareBtn').href=`https://x.com/intent/post?text=${encodeURIComponent('My Backpack Capital Composer plan: '+$('#cardTitle').textContent+' — '+$('#cardSubtitle').textContent)}&url=${encodeURIComponent(encodePlan())}`}
function openShare(){renderModal();$('#shareModal').classList.add('open');$('#shareModal').setAttribute('aria-hidden','false')}
function closeShare(){ $('#shareModal').classList.remove('open');$('#shareModal').setAttribute('aria-hidden','true') }
$('#capital').addEventListener('input',e=>{state.capital=Math.max(100,Number(e.target.value)||100);recalculate();}); $$('.quick-row button').forEach(btn=>btn.addEventListener('click',()=>{$$('.quick-row button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');state.capital=Number(btn.dataset.capital);$('#capital').value=state.capital;recalculate();})); $('#horizon').addEventListener('change',e=>{state.horizon=Number(e.target.value);recalculate()}); $('#risk').addEventListener('change',e=>{state.risk=e.target.value;recalculate()}); $('#goal').addEventListener('change',e=>{state.goal=e.target.value;recalculate()}); [['lendingRate','lendingRate'],['borrowRate','borrowRate']].forEach(([id,key])=>$(`#${id}`).addEventListener('input',e=>{state[key]=Math.max(0,Number(e.target.value)||0);recalculate()})); $$('.preset').forEach(btn=>btn.addEventListener('click',()=>setPreset(btn.dataset.preset))); $('#resetBtn').addEventListener('click',reset); $('#copyBtn').addEventListener('click',openShare); $('#shareBtn').addEventListener('click',openShare); $('#modalCopyBtn').addEventListener('click',copyPlan); $$('[data-close-share]').forEach(el=>el.addEventListener('click',closeShare)); document.addEventListener('keydown',e=>{if(e.key==='Escape')closeShare()}); $$('.seg').forEach(btn=>btn.addEventListener('click',()=>{$$('.seg').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.mode=btn.dataset.mode;document.body.classList.toggle('advanced',state.mode==='advanced');recalculate()}));
function setRadarDemo(){const d=state.radarData||{total:2000,exposure:900,idle:500,borrowed:200},total=d.total,exposure=d.exposure,idle=d.idle,borrowed=d.borrowed,move=Number($('#marketMove').value||10),extra=Number($('#newPosition').value||0);$('#radarTotal').textContent=money(total);$('#radarExposure').textContent=money(exposure);$('#radarExposureSub').textContent=`${total?Math.round(exposure/total*100):0}% of account`;$('#radarIdle').textContent=money(idle);$('#radarBorrowed').textContent=money(borrowed);const impact=(exposure+extra)*move/100;$('#whatifImpact').textContent=`-${money(impact)}`;const score=extra>500?58:Math.max(35,Math.min(96,Math.round(86-(exposure/Math.max(total,1))*30-(borrowed/Math.max(total,1))*25)));$('#healthScore').textContent=score;$('#healthBadge').textContent=state.radarData?'Manual':'Demo';$('#snapshotTitle').textContent=`Backpack account health · ${score}/100`;$('#snapshotCopy').textContent=extra>500?'New position reduces the safety buffer':state.radarData?'Manual read-only snapshot':'Balanced composition · read-only snapshot'}
function openConnect(){ $('#connectModal').classList.add('open');$('#connectModal').setAttribute('aria-hidden','false') } function closeConnect(){ $('#connectModal').classList.remove('open');$('#connectModal').setAttribute('aria-hidden','true');if($('#apiKeyInput'))$('#apiKeyInput').value='';if($('#apiSecretInput'))$('#apiSecretInput').value=''; }
initFaq(); loadPlan(); renderAllocations(); recalculate(); setRadarDemo();
$('#radarCopyBtn').addEventListener('click',openRadarShare);$('#radarShareBtn').addEventListener('click',openRadarShare);
$$('.seg').forEach(btn=>btn.addEventListener('click',()=>{const view=btn.dataset.view;if(!view)return;$('#radarView').classList.toggle('hidden',view!=='radar');$('#composerView').classList.toggle('hidden',view!=='composer');}));
$('#connectBtn').addEventListener('click',openConnect);$('#demoBtn').addEventListener('click',()=>{$('#connectionState').classList.remove('hidden');setRadarDemo();toast('Demo account loaded')});$('#modalDemoBtn').addEventListener('click',()=>{closeConnect();$('#connectionState').classList.remove('hidden');setRadarDemo();toast('Demo account loaded')});$('#apiHelpBtn').addEventListener('click',()=>toast('Read-only API connection is next'));$('#disconnectBtn').addEventListener('click',()=>{$('#connectionState').classList.add('hidden');toast('Disconnected')});$('#radarCopyBtn').addEventListener('click',openShare);$('#radarShareBtn').addEventListener('click',openShare);$('#marketMove').addEventListener('change',setRadarDemo);$('#newPosition').addEventListener('input',setRadarDemo);$$('[data-close-connect]').forEach(el=>el.addEventListener('click',closeConnect));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeConnect()});
function openRadarShare(){openShare();$('#modalCard').innerHTML=`<div class="share-brand"><img src="./public/backpack-glyph.png" alt="" /><span>BACKPACK / CAPITAL RADAR</span></div><div class="share-main"><div><span class="muted">ACCOUNT HEALTH SNAPSHOT</span><strong>Demo account · ${$('#healthScore').textContent}/100</strong><p>${$('#snapshotCopy').textContent}</p></div></div><div class="share-foot"><span>Read-only analysis · variable outcomes</span><span>RADAR / ${$('#healthScore').textContent}</span></div>`;$('#xShareBtn').href=`https://x.com/intent/post?text=${encodeURIComponent('My Backpack Capital Radar health score is '+$('#healthScore').textContent+'/100. '+$('#snapshotCopy').textContent)}`}
async function connectLive(){
  const key=$('#apiKeyInput').value.trim(),secret=$('#apiSecretInput').value.trim(),status=$('#apiStatus'),button=$('#apiConnectBtn');
  if(!key||!secret){status.textContent='Enter both values from your Backpack read-only key.';return}
  button.disabled=true;status.textContent='Reading your account securely…';
  try{
    const response=await fetch('/api/backpack',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({apiKey:key,apiSecret:secret})});
    const result=await response.json().catch(()=>({ok:false,error:'The connection endpoint returned an unreadable response.',code:'BAD_RESPONSE'}));
    if(!response.ok||!result.ok)throw new Error(result.error||'Connection failed');

    const data=result.data||{},positions=Array.isArray(data.positions)?data.positions:[],borrowLend=Array.isArray(data.borrowLend)?data.borrowLend:[],collateral=data.collateral&&typeof data.collateral==='object'?data.collateral:{};
    const debts=borrowLend.filter(x=>Number(x.netQuantity)<0),exposureFromPositions=positions.reduce((sum,p)=>sum+Math.abs(Number(p.netExposureNotional||0)),0),exposureFromCollateral=Math.abs(Number(collateral.netExposureFutures||0)),exposure=exposureFromPositions||exposureFromCollateral;
    const total=Number(collateral.netEquity||collateral.assetsValue||0),available=Number(collateral.netEquityAvailable||0),borrowedValue=Number(collateral.borrowLiability||collateral.liabilitiesValue||0);
    const marginFraction=Number(collateral.marginFraction),score=Number.isFinite(marginFraction)&&marginFraction>0?Math.max(35,Math.min(96,Math.round(70+marginFraction*100))):Math.max(35,Math.min(96,Math.round(82-(positions.length*3)-(debts.length*5))));
    $('#connectionState').classList.remove('hidden');$('#healthBadge').textContent='Live';$('#healthScore').textContent=score;$('#healthHeadline').textContent=score>70?'Healthy, keep monitoring exposure':'Review exposure before adding risk';$('#healthCopy').textContent=`Live snapshot received: ${positions.length} open position${positions.length===1?'':'s'}${debts.length?` and ${debts.length} borrow/lend position${debts.length===1?'':'s'}`:''}.`;
    if(total>0)$('#radarTotal').textContent=money(total);
    $('#radarExposure').textContent=exposure?money(exposure):'$0';$('#radarExposureSub').textContent='live notional exposure';
    if(available>0){$('#radarIdle').textContent=money(available);$('#radarIdle').nextElementSibling.textContent='available equity (live)'}else{$('#radarIdle').textContent='—';$('#radarIdle').nextElementSibling.textContent='not returned by this account'}
    if(borrowedValue>0){$('#radarBorrowed').textContent=money(borrowedValue);$('#radarBorrowedSub').textContent='liability value (live)'}else{$('#radarBorrowed').textContent=debts.length?`${debts.length} position${debts.length===1?'':'s'}`:'$0';$('#radarBorrowedSub').textContent=debts.length?'open borrow/lend positions':'no open borrow balance'}
    $('#snapshotTitle').textContent=`Backpack account health · ${score}/100`;$('#snapshotCopy').textContent='Live read-only snapshot';
    const warningCount=Array.isArray(result.warnings)?result.warnings.length:0;status.textContent=warningCount?`Connected. Balances loaded; ${warningCount} optional detail${warningCount===1?' is':'s are'} unavailable for this account.`:'Connected. Credentials discarded from this browser.';closeConnect();toast(warningCount?'Backpack connected with partial details':'Backpack account connected');
  }catch(error){status.textContent=error.message||'Connection failed. Check the key and Read Only permission.';toast('Could not connect')}
  finally{button.disabled=false;$('#apiKeyInput').value='';$('#apiSecretInput').value=''}
}
$('#apiConnectBtn').addEventListener('click',connectLive);
document.addEventListener('click',e=>{if(e.target.closest('#tipBtn'))openTip();if(e.target.closest('#manualBtn'))openManual();if(e.target.closest('#copyTipBtn')){navigator.clipboard?.writeText($('#tipAddress').textContent.trim()).then(()=>toast('Solana address copied')).catch(()=>toast('Select the address to copy'))}});
function openManual(){ $('#manualModal').classList.add('open');$('#manualModal').setAttribute('aria-hidden','false') } function closeManual(){ $('#manualModal').classList.remove('open');$('#manualModal').setAttribute('aria-hidden','true') }
function applyManualSnapshot(){const total=Math.max(0,Number($('#manualTotal').value)||0),spot=Math.max(0,Number($('#manualSpot').value)||0),futures=Math.max(0,Number($('#manualFutures').value)||0),stocks=Math.max(0,Number($('#manualStocks').value)||0),lending=Math.max(0,Number($('#manualLending').value)||0),reserve=Math.max(0,Number($('#manualReserve').value)||0),borrowed=Math.max(0,Number($('#manualBorrowed').value)||0);state.radarData={total,exposure:spot+futures+stocks,idle:lending+reserve,borrowed};closeManual();$('#connectionState').classList.remove('hidden');$('#connectionLabel').textContent='Manual snapshot · nothing shared';setRadarDemo();toast('Manual Radar generated')}
$('#manualBtn').addEventListener('click',openManual);$$('[data-close-manual]').forEach(el=>el.addEventListener('click',closeManual));$('#manualApplyBtn').addEventListener('click',applyManualSnapshot);
function openTip(){ $('#tipModal').classList.add('open');$('#tipModal').setAttribute('aria-hidden','false') } function closeTip(){ $('#tipModal').classList.remove('open');$('#tipModal').setAttribute('aria-hidden','true') }
$('#tipBtn').addEventListener('click',openTip);$$('[data-close-tip]').forEach(el=>el.addEventListener('click',closeTip));$('#copyTipBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#tipAddress').textContent.trim());toast('Solana address copied')}catch(e){toast('Copy failed — select the address')}});
